#ifndef CONSTANTS_H
#define CONSTANTS_H

const int SND_FAILURE = EXIT_FAILURE;
const int SND_SUCCESS = EXIT_SUCCESS;
const int RCV_FAILURE = EXIT_FAILURE;
const int RCV_SUCCESS = EXIT_SUCCESS;

#endif